### ISSUE TITLE
Missing Files 

### ISSUE THREAD

**Issue by syedbaqarrizvi** [MetaCDN/videojs-shaka-player#12]
In example file i can see shaka html. i am unable to find 2 files from it 

1) /dist/js/shaka-player.compiled.debug.js
2) /dist/css/videojs-icons.css

Unable to find in in src area

**Comment by jbroberg** [comment]
Hi there - did you run ./build.sh and did it complete successfully?

**Comment by syedbaqarrizvi** [comment]
Hey Jbroberg,
you are awesome That really helps,I do have created a live example as well but MPD and The resolution button is not showing . I know you will find in second what i am missing .

http://codepen.io/baqarrizvi/pen/XdEwYR?editors=1010

Many Thanks
Baqarrizvi

**Comment by jbroberg** [comment]
Hi Baqarrizvi

You have two sources in there - mp4 and mpd. It's playing back the MP4 which is likely why you are not seeing the resolution button.

**Comment by syedbaqarrizvi** [comment]
Hey Jbroberg,
Thanks for you reply from your important time actaully when i am trying to play .mpd file i am having these error ,

![image](https://cloud.githubusercontent.com/assets/15075559/14579655/a8322a2c-03ca-11e6-9336-b9243e9498e3.png)

I hope you will let me know why its not playing 

Many Thanks
