### ISSUE TITLE
Error On video js 5.9.2 

### ISSUE THREAD

**Issue by syedbaqarrizvi** [MetaCDN/videojs-shaka-player#14]
Hello jbroberg,
Its very amazing to see your version of the combine shaka and VIdeo.js the most awesome thing in you code is the Resolution selector which seems pretty good actually. But i am having 3 Errors after putting like your example . its Playing mp4 is not working in .MPD

1) VIDEOJS: ERROR: The "Shaka" tech is undefined. Skipped browser support check for that 
`// call appropriate log function
  if (console[type].apply) {
    console[type].apply(console, argsArray);`

2) Uncaught TypeError: Cannot read property 'extend' of undefined(anonymous function) @ videojs.shaka.dev.js.
`videojs.Shaka = videojs.Html5.extend({`

3) Uncaught ReferenceError: goog is not defined .
`goog.require('shaka.Player');
`
Screen shot 

![image](https://cloud.githubusercontent.com/assets/15075559/14811725/d7986390-0bb2-11e6-9fde-38153757f8f1.png)

Hope you will respond me from your precious Time 

Many Thanks ,
baqarrizvi

**Comment by jrudio** [comment]
To help anyone else that stumbled onto this issue.

As recommended elsewhere in this repo, switch to the [vjs5 branch](https://github.com/MetaCDN/videojs-shaka-player/tree/vjs5)

**Comment by jbroberg** [comment]
Hi there.

Sorry for taking so long to respond. I've just released a new version with a new build system. Read the updated README.md, give it a go and take a look at the example in example/shaka.html

If you are still having issues please share a hosted page that we can check out.
