### ISSUE TITLE
JFYI: Shaka 2 coming soon

### ISSUE THREAD

**Issue by joeyparrish** [MetaCDN/videojs-shaka-player#7]
JFYI, Shaka team is hard at work on Shaka 2, which will have a new API.  You can see a preview of the work-in-progress on the [preview branch](https://github.com/google/shaka-player/tree/preview/).  We also published a [redesign doc](https://github.com/google/shaka-player/blob/preview/docs/design/REDESIGN.md) with a roughed-out version of the new APIs and diagrams of the new architecture.

I'll update this ticket once we go into beta so that you have a chance to give feedback on the API and start working on updates to your videojs plugin to support Shaka 2.  We expect the official release of Shaka 2.0.0 by end of March.  Thanks!

**Comment by jbroberg** [comment]
cheers @joeyparrish thanks for the heads up!

**Comment by joeyparrish** [comment]
We've just released [v2.0.0-beta](https://github.com/google/shaka-player/tree/v2.0.0-beta) on github & npm.  Let us know what you think.

We're still working on the v2 upgrade guide, but we have [tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html) on several other topics already.  Hopefully that will be enough to get you started, and you can always reach out via email or github if there's anything we can do to help with the transition.

Thanks!

**Comment by joeyparrish** [comment]
@jbroberg, we've just released [v2.0.0-beta3](https://github.com/google/shaka-player/tree/v2.0.0-beta3) on github & npm.  The upgrade guide is available [here](http://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade.html).  Let us know what you think!

**Comment by joeyparrish** [comment]
@jbroberg, v2.0.0 is officially out of beta.

**Comment by jbroberg** [comment]
Hi @joeyparrish - sorry this took forever. I've upgraded/ported the plugin to use shaka2. Very lightly tested so far but seems to work.

**Comment by jbroberg** [comment]
Thanks for the heads up @joeyparrish.
